name: Build RustDeskIddDriver Win7
on:
  workflow_dispatch:
  workflow_call:
#  push:
#    branches:
#      - main

env:
  TAG_NAME: RustDeskIddDriver7

jobs:
  build_Win7:
    strategy:
      matrix:
        # configuration: [Debug, Release]
        configuration: [Release]
        platform: [x64]
        target: [Windows7]

    runs-on: windows-2022

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
   
      - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
        shell: powershell
        run: |
          $VS_BTOOLS_EXE="vs_buildtools.exe"
          $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
          Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
          Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
          "--add", "Microsoft.VisualStudio.Component.VC.140", `
          "--add", "Microsoft.VisualStudio.Component.MSBuild.140", `
          "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
          "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
        
      - name: Set Solution name
        shell: bash
        run: |
          echo "Solution_Path=${{ env.TAG_NAME }}.sln" >> $GITHUB_ENV

      - name: search msbuild.exe
        continue-on-error: true
        shell: cmd
        run: |
          echo "current dir 1"
          dir
          echo %cd% > crt-dir
          set /p crt_dir=<crt-dir
          echo "crt-dir=" %crt-dir%
          pushd "C:\Program Files"
          echo "current dir 2"
          dir
          echo 'dir /b /s msbuild.exe 1'
          dir /b /s msbuild.exe
          dir /b /s msbuild.exe | grep amd64 >%crt_dir%\msbuild_path-1.txt
          popd

          # D:\a\RustDeskIddDriver\RustDeskIddDriver
          pushd "C:\Program Files (x86)"
          echo "current dir 3"
          dir
          echo 'dir /b /s msbuild.exe 2'
          dir /b /s msbuild.exe
          dir /b /s msbuild.exe | grep amd64 >%crt_dir%\msbuild_path-2.txt
          popd

          echo "current dir 4"
          dir
          echo "msbuild_path1.txt"
          type msbuild_path1.txt
          echo "msbuild_path2.txt"
          type msbuild_path2.txt          
          set /p msbuild_path2=<msbuild_path2.txt
          if (NOT .%msbuild_path2%==.) set PATH=%msbuild_path2%;%PATH%

      - name: Upload files
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: |
            msbuild_path1.txt
            msbuild_path2.txt

      - name: dir program files
        continue-on-error: true
        shell: cmd
        run: |
          dir /s "C:\Program Files\" >program-files.dir
          dir /s "C:\Program Files (x86)\" >program-files-86.dir
          
      - name: Create Zip Archive with lists
        continue-on-error: true
        uses: deep-soft/zip-release@v2
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}-list.zip'
          directory: '.'
          exclusions: '*.map *.pdb ./.git/* .git/*'
          recursive_exclusions: '*.map *.pdb'
          path: 'program-files.dir program-files-86.dir msbuild_path.txt'
          
      - name: Upload zip
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: ${{ env.ZIP_RELEASE_ARCHIVE }}
          
      - name: Add MSBuild to PATH
        continue-on-error: true
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: '[14.0]'
    
      - name: Build solution
        run: |
          msbuild ${{ env.Solution_Path }} /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }} /property:TargetVersion=${{ env.Target }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}

      - name: Create Zip Archive Release
        uses: deep-soft/zip-release@v2
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}.zip'
          directory: 'x64/Release'
          inclusions: '*.cer *.inf *.dll'
          exclusions: '*.map *.pdb ./.git/* .git/*'
          recursive_exclusions: '*.map *.pdb'
          path: '${{ env.TAG_NAME }}.cer ${{ env.TAG_NAME }}.inf ${{ env.TAG_NAME }}.dll'

      - name: Upload zip
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Publish
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          # tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}
          files: |
            ${{ env.ZIP_RELEASE_ARCHIVE }}
