name: Build RustDeskIddDriver Win7
on:
  workflow_dispatch:
  workflow_call:
#  push:
#    branches:
#      - main

env:
  TAG_NAME: RustDeskIddDriver7

jobs:
  build_Win7:
    strategy:
      matrix:
        # configuration: [Debug, Release]
        configuration: [Release]
        platform: [x64]
        target: [Windows7]

    runs-on: windows-2022

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
   
      - name: Install MSVC 2015 (v140) and Windows 8.1 SDK
        shell: powershell
        run: |
          $VS_BTOOLS_EXE="vs_buildtools.exe"
          $VS_BTOOLS_URI="https://aka.ms/vs/15/release/vs_buildtools.exe"
          Invoke-WebRequest -Uri $VS_BTOOLS_URI -OutFile $VS_BTOOLS_EXE
          Start-Process -FilePath ./vs_BuildTools.exe -ArgumentList `
          "--add", "Microsoft.VisualStudio.Component.VC.140", `
          "--add", "Microsoft.VisualStudio.Component.MSBuild.140", `
          "--add", "Microsoft.VisualStudio.Component.Windows81SDK", `
          "--quiet", "--norestart", "--force", "--wait" -Wait -PassThru
        
      - name: Set Solution name
        shell: bash
        run: |
          echo "Solution_Path=${{ env.TAG_NAME }}.sln" >> $GITHUB_ENV

      - name: search msbuild.exe
        continue-on-error: true
        shell: cmd
        run: |
          mkdir D:\tmp
          echo %cd% > D:\tmp\crt_dir.txt
          type D:\tmp\crt_dir.txt
          set /p crt_dir=<D:\tmp\crt_dir.txt
          echo "crt_dir=" %crt_dir%
          pushd "C:\Program Files\Microsoft Visual Studio"
          echo 'dir /b /s msbuild.exe 1'
          dir /b /s msbuild.exe | grep amd64 >D:\tmp\msbuild.txt
          popd
          echo D:\tmp\msbuild.txt
          type D:\tmp\msbuild.txt
          set /p msbuild<D:\tmp\msbuild.txt
          echo "msbuild=" %msbuild%
          echo MSBUILD_EXE=%msbuild% >> $GITHUB_ENV
          :: extract msbuild path not working
          :: for %i in ("%msbuild%") do set msbuild_path=%~dpi
          :: echo %msbuild_path%
          :: echo %msbuild_path% > D:\tmp\msbuild_path.txt
          :: set PATH=%msbuild_path%;%PATH%
          :: echo "PATH=%msbuild_path%;%PATH%" >> $GITHUB_ENV

      - name: Create Zip Archive with lists
        continue-on-error: true
        uses: deep-soft/zip-release@v2
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}-msbuild-txt.zip'
          directory: '.'
          exclusions: '*.map *.pdb ./.git/* .git/*'
          recursive_exclusions: '*.map *.pdb'
          path: 'D:\tmp\msbuild.txt'

      - name: Publish
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          # tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}
          files: |
            ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Upload files
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: |
            D:\tmp\msbuild.txt

#      - name: dir program files
#        continue-on-error: true
#        shell: cmd
#        run: |
#          dir /s "C:\Program Files\" >program-files.dir
#          dir /s "C:\Program Files (x86)\" >program-files-86.dir
#          
#      - name: Create Zip Archive with lists
#        continue-on-error: true
#       uses: deep-soft/zip-release@v2
#        env:
#          Configuration: ${{ matrix.configuration }}
#          Platform: ${{ matrix.platform }}
#          Target: ${{ matrix.target }}
#        with:
#          type: 'zip'
#          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}-list.zip'
#          directory: '.'
#          exclusions: '*.map *.pdb ./.git/* .git/*'
#          recursive_exclusions: '*.map *.pdb'
#          path: 'program-files.dir program-files-86.dir D:\tmp\msbuild_path-1.txt D:\tmp\msbuild_path-2.txt'
#          
#      - name: Upload zip
#        continue-on-error: true
#        uses: deep-soft/upload-artifact@main
#        with:
#          name: ${{ env.TAG_NAME }}
#          path: ${{ env.ZIP_RELEASE_ARCHIVE }}
#          
#      - name: Add MSBuild to PATH
#        continue-on-error: true
#        uses: microsoft/setup-msbuild@v1.3
#        with:
#          vs-version: '[14.0]'

      - name: Build solution
        shell: cmd
        run: |
          ${{ env.MSBUILD_EXE }} ${{ env.Solution_Path }} /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }} /property:TargetVersion=${{ env.Target }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}

      - name: Create Zip Archive Release
        uses: deep-soft/zip-release@v2
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}.zip'
          directory: 'x64/Release'
          inclusions: '*.cer *.inf *.dll'
          exclusions: '*.map *.pdb ./.git/* .git/*'
          recursive_exclusions: '*.map *.pdb'
          path: '${{ env.TAG_NAME }}.cer ${{ env.TAG_NAME }}.inf ${{ env.TAG_NAME }}.dll'

      - name: Upload zip
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Publish
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          # tag_name: ${{ env.TAG_NAME }}-${{ env.VERSION }}
          files: |
            ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: dir program files
        continue-on-error: true
        shell: cmd
        run: |
          dir /s "C:\Program Files\" >D:\tmp\program-files.dir
          dir /s "C:\Program Files (x86)\" >D:\tmp\program-files-86.dir
          
      - name: Create Zip Archive with lists
        continue-on-error: true
        uses: deep-soft/zip-release@v2
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Target: ${{ matrix.target }}
        with:
          type: 'zip'
          filename: '${{ env.TAG_NAME }}-${{ env.Configuration }}-${{ env.Platform }}-${{ env.Target }}-list.zip'
          directory: '.'
          exclusions: '*.map *.pdb ./.git/* .git/*'
          recursive_exclusions: '*.map *.pdb'
          path: 'D:\tmp\program-files.dir D:\tmp\program-files-86.dir'
          
      - name: Upload zip
        continue-on-error: true
        uses: deep-soft/upload-artifact@main
        with:
          name: ${{ env.TAG_NAME }}
          path: ${{ env.ZIP_RELEASE_ARCHIVE }}
